#pragma once
#include "NativeGameplayTags.h"

namespace AetherGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchPartySlot1)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchPartySlot2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchPartySlot3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchPartySlot4);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_NormalAttack);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AuraGauge);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Pyro);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Hydro);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Electro);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Cryo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Anemo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Geo);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_SwitchPartySlot)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(NormalAttack_ComboWindow_Opened)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(NormalAttack_ComboWindow_Closed)
	
}
